package com.ai.assist.documents

import org.json.JSONArray
import org.json.JSONObject

object DocumentOutlineParser {
    fun parseOrFallback(content: String, topic: String, slideCount: Int): DocumentOutline {
        val jsonText = extractJson(content) ?: return fallback(topic, slideCount)
        return runCatching {
            val json = JSONObject(jsonText)
            val slidesJson = json.optJSONArray("slides") ?: JSONArray()
            val slides = buildList {
                for (index in 0 until slidesJson.length()) {
                    val slide = slidesJson.optJSONObject(index) ?: continue
                    val bulletsJson = slide.optJSONArray("bullets") ?: JSONArray()
                    val bullets = buildList {
                        for (bulletIndex in 0 until bulletsJson.length()) {
                            val bullet = bulletsJson.optString(bulletIndex).trim()
                            if (bullet.isNotBlank()) add(bullet)
                        }
                    }
                    add(
                        SlideOutline(
                            title = slide.optString("title").ifBlank { "Slide ${index + 1}" },
                            bullets = bullets.ifEmpty { listOf("Key point", "Detail", "Next step") },
                            speakerNote = slide.optString("speakerNote").takeIf { it.isNotBlank() },
                        ),
                    )
                }
            }.ifEmpty { fallback(topic, slideCount).slides }
            DocumentOutline(
                title = json.optString("title").ifBlank { topic },
                subtitle = json.optString("subtitle").ifBlank { "Generated by AI Assist Lab" },
                slides = slides.take(slideCount.coerceIn(1, 12)),
            )
        }.getOrElse { fallback(topic, slideCount) }
    }

    fun fallback(topic: String, slideCount: Int): DocumentOutline {
        val count = slideCount.coerceIn(1, 12)
        val slideTitles = listOf(
            "Overview",
            "Background",
            "Core Ideas",
            "Architecture",
            "Use Cases",
            "Next Steps",
            "Risks",
            "Summary",
        )
        return DocumentOutline(
            title = topic.ifBlank { "Untitled Document" },
            subtitle = "Lightweight template generated on device",
            slides = (0 until count).map { index ->
                val title = slideTitles.getOrElse(index) { "Section ${index + 1}" }
                SlideOutline(
                    title = title,
                    bullets = listOf(
                        "Introduce $topic from the user's perspective.",
                        "Add concrete examples and supporting details.",
                        "Keep the slide concise for mobile editing.",
                    ),
                )
            },
        )
    }

    private fun extractJson(content: String): String? {
        val start = content.indexOf('{')
        val end = content.lastIndexOf('}')
        return if (start >= 0 && end > start) content.substring(start, end + 1) else null
    }
}
